In [2]:
import numpy as np

1. Most important object defined in NumPy is an N-dimensional array type called "ndarray"
2. The collection of items of the same type.And every Item takes same size of block in the memory
3. Items in the collection can be accessed using a zero-based index.
4. Each element in ndarray is an object of "data-type object (called dtype)".
5. Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types

In [66]:
a0 = np.array([1,2,3])# Creation of One Dimensional Array
a0

array([1, 2, 3])

In [54]:
a1 = np.array([[1,2,3],[4,5,6]]) #Creation of multi dimensional Array

a1

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
a2 = np.array([[1,4],[2,5],[3,6]]) #Creation of multi dimensional Array
a2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
np.array([1,2,3], dtype = complex) #Using of Dtype argument while creating the array
#dtype - Desired data type of array, optional

array([1.+0.j, 2.+0.j, 3.+0.j])

# Data Types
1. These "numerical" datatypes are instances of dtype (data-type) objects, each having unique characteristics. The dtypes are available as np.bool_, np.float32, etc
#### dtypes: int_<8,16,32,64>, bool_,float_<16,32,64>,complex_<64,128> ,  string_, unicode_ e.t.c

In [23]:
#dtype function returns the datatype of a dtype

np.dtype(np.bool_)


dtype('bool')

 ## Creating the structured data with array() and dtype()

In [31]:
# Example-1
dt = np.dtype([('age', np.int16)]) #List of tuples inside the dtype object

students = np.array([23,32,43], dtype =  dt)

students['age']

array([23, 32, 43], dtype=int16)

In [52]:
#Example-2

dt = np.dtype([('age',np.int16),('points',np.int8)])

pointTable = np.array([(11,1),(22,2),(33,3)], dtype = dt) 
#Note the parenthesis instead of the square brackets 
# Each set of values in the parenthesis forms a row(Records) of the structured data and each value represents a column(Feature)
# IN the array creation, not structured data, we use Square brackets in to create a multidimensional arrays 
print(pointTable['points'])

print(pointTable['age'])

[1 2 3]
[11 22 33]


# Attributes on an numpy array
  1. Shape - gives rows x columns as a tuple
  2. Reshape - changes the shape of the array
  3. ndim - gives the dimension of the array
  4. itemsize - returns the length of each element of array in bytes.
  5. flags - returns different properties of the array

In [62]:
# SHAPE

print(pointTable.shape) # You can observe that the strucuted data only Rows count.........that is no.of records not even a mention od feature
print(a1.shape) # In the arrays the out put is row x shape
print(a2.shape)

(3,)
(2, 3)
(3, 2)


In [65]:
# Reshape

print(a1.reshape(3,2)) # You can see the a1(2,3) is chaged to shape of (3,2)

[[1 2]
 [3 4]
 [5 6]]


In [70]:
#ndim
#print(pointTable.ndim)
print(a0.ndim)
print(a1.ndim)
print(a2.ndim)

1
2
2


In [76]:
# Example

testArray = np.arange(24)#Gives a range of values starting from 0 to the argument-1

print(testArray.ndim)

print(testArray.reshape(2,3,4))

print(testArray.reshape(2,3,4).ndim)

1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


In [78]:
#itemsize

print(a0.itemsize)
print(a1.itemsize)
print(a2.itemsize)

4
4
4


In [79]:
#flags

print(a0.flags)
print(a1.flags)
print(a2.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


# Array Creation Routines
####  Default dtype is float 
#### Default Order is 'C'
1. empty(shape,dtype=<>,order = '<C,F>')--> creates an empty array of specified shape and dtype.
2. zeros(shape,dtype=<>,order = '<C,F>')--> Returns a new array of specified size, filled with zeros.
3. ones(shape,dtype=<>,order = '<C,F>') --> Returns a new array of specified size and type, filled with ones.

In [14]:
np.empty([3,2],dtype = np.float_, order = 'C')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.zeros([3,2],dtype = np.float_, order = 'C')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.ones([3,2],dtype = np.int64, order = 'C')

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

# Array From Existing Data

1. asarray(a, dtype = None, order = None) # a is any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists --> converting Python sequence into ndarray.
2. fromiter(iterable, dtype, count = -1) --> builds an ndarray object from any iterable object. A new one-dimensional array is returned by this function.

In [19]:
a = [(1,2),(2,3)]

b = [[1,2],(2,3)]

print(np.asarray(a))

print(np.asarray(b, dtype=np.float64))

[[1 2]
 [2 3]]
[[1. 2.]
 [2. 3.]]


In [25]:
listA = range(10)

iterableA = iter(listA)

np.fromiter(iterableA, dtype = np.int_)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Array From Numerical Ranges

1. arange(start, stop, step, dtype) --> returns an ndarray object containing evenly spaced values within a given range
2. linspace(start, stop, num, endpoint, retstep, dtype) --> similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified
3. logspace(start, stop, num, endpoint, base, dtype) --> returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.

In [29]:
print(np.arange(1,100,5, np.int_))
print(np.arange(1.3)) # Default Start = 0 , Step = 1, dtype=type of stop given as argument

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[0. 1.]


In [31]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [34]:
np.logspace(1,10,num = 10, base = 2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

# Indexing & Slicing
1. Contents of ndarray object can be accessed and modified by indexing or slicing
2. ndarray object follows zero-based index
3. Three types of indexing methods are available − field access, basic slicing and advanced indexing.

In [43]:
a = np.arange(1,99,1)
a[2:7:3] # Start:Stop:Step=1

array([3, 6])

In [51]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a[1:])
print('\n')
print(a[0:1])

[[3 4 5]
 [4 5 6]]


[[1 2 3]]


#### Boolean Indexing - Can be used to fetch elements of an array based on a condition.

In [55]:
# BOOLEAN INDEXING - advanced indexing is used when the resultant object is meant to be the result of Boolean operations, such as comparison operators.
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('Our array is:') 
print(a) 
print('\n')
print(a[a<5])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


[1 2 3 3 4 4]


In [64]:
# Print all "nan" values
# ~ complement
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print('Our array is:') 
print(a) 
print('\n')

print(a[~np.isnan(a)])

Our array is:
[nan  1.  2. nan  3.  4.  5.]


[1. 2. 3. 4. 5.]


In [65]:
#Print All Complex Numbers from an array
a = np.array([1, 2+6j, 5, 3.5+5j])
print('Our array is:') 
print(a) 
print('\n')

print(a[np.iscomplex(a)])

Our array is:
[1. +0.j 2. +6.j 5. +0.j 3.5+5.j]


[2. +6.j 3.5+5.j]


# Broadcasting
##### refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements
###### The following figure demonstrates how array b is broadcast to become compatible with a
<img src="https://www.tutorialspoint.com/numpy/images/array.jpg" alt="Array" title="Broadcasting on two dissimilar arrays" />

In [66]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0])

print(a+b)

[[ 1.  1.  1.]
 [11. 11. 11.]
 [21. 21. 21.]
 [31. 31. 31.]]


In [72]:
a = np.array([[1],[2]])
print(a)
print('\n')
b = np.array([[1,2]])
print(b)
print('\n')

print(a+b)

[[1]
 [2]]


[[1 2]]


[[2 3]
 [3 4]]


# Iterating Over Array

1. numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.
2. The order of iteration is chosen to match the memory layout of an array, without considering a particular ordering.
3. If the same elements are stored using F-style order, the iterator chooses the more efficient way of iterating over an array.

In [80]:
a = np.arange(9)
a = a.reshape(3,3)

#Op-flag tells in which mode to open

for element in np.nditer(a, order= 'F', op_flags= ['readwrite']): 
    print(element)

0
3
6
1
4
7
2
5
8


# Array Manipulation

### Changing Shape

In [81]:
a = np.arange(9)
print(a)
print('\n')
a = a.reshape(3,3)
print(a)

[0 1 2 3 4 5 6 7 8]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [84]:
# function returns a 1-D iterator over the array. It behaves similar to Python's built-in iterator.
a = np.arange(8).reshape(2,4) 

print(a)
print('\n')

a.flat[5]

[[0 1 2 3]
 [4 5 6 7]]




5

In [88]:
a = np.arange(8).reshape(2,4) 

print(a)
print('\n')

print(a.flatten()) #order<C,F> can also be used as a parameter within the function
print('\n')

print(a.flatten(order= 'F'))

[[0 1 2 3]
 [4 5 6 7]]


[0 1 2 3 4 5 6 7]


[0 4 1 5 2 6 3 7]


In [90]:
# returns a flattened one-dimensional array. A copy is made only if needed. The returned array will have the same type as that of the input array. The function takes one parameter.

a = np.arange(8).reshape(2,4) 

print(a)
print('\n')

print(a.ravel()) #order<C,F> can also be used as a parameter within the function
print('\n')

print(a.ravel(order= 'F'))

[[0 1 2 3]
 [4 5 6 7]]


[0 1 2 3 4 5 6 7]


[0 4 1 5 2 6 3 7]


### Transpose Operations

In [92]:
a = np.arange(12).reshape(3,4) 
print(a)
print('\n')

print(np.transpose(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [93]:
a = np.arange(12).reshape(3,4) 
print(a)
print('\n')

print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Joining Arrays

In [96]:
a = np.array([[1,2],[3,4]]) 

print('First array:')
print(a) 
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Second array:') 
print(b)
print('\n')  
# both the arrays are of same dimensions 

print('Joining the two arrays along axis 0(Rows):') 
print(np.concatenate((a,b))) 
print('\n')  

print('Joining the two arrays along axis 1(Columns):')
print(np.concatenate((a,b),axis = 1))

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0(Rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1(Columns):
[[1 2 5 6]
 [3 4 7 8]]


In [104]:
#Horizantal Stack-------------------Columnwise Stacking
a = np.array([[1,2],[3,4]])
print(a)
print('\n')
b = np.array([[5,6],[7,8]])
print(b)
print('\n')
print(np.hstack((a,b)))

[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


In [103]:
#Vertical Stack-------------------row-wise Stacking
a = np.array([[1,2],[3,4]])
print(a)
print('\n')
b = np.array([[5,6],[7,8]])
print(b)
print('\n')
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Splitting Arrays

In [105]:
a = np.arange(9) 

print(a)
print('\n')

print(np.split(a,3)) # Split the array in 3 equal-sized subarrays
print('\n')

print(np.split(a,[4,7])) #Split the array at positions indicated in 1-D array

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [114]:
# Horizantal Split - Equal Split Columnwise

a = np.arange(16).reshape((4,4))
print(a)
print('\n')

print(np.hsplit(a,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [115]:
#Vertical Split - Equal Split happens Row wise

a = np.arange(16).reshape((4,4))
print(a)
print('\n')
print(np.vsplit(a,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# Adding / Removing Elements

In [119]:
a = np.arange(9)
print(a)
print('\n')

print(np.reshape(a,(3,3))) # Usage 1
print('\n')
print(a.reshape((3,3))) # Usage 2

[0 1 2 3 4 5 6 7 8]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [124]:
# The dimensions of the input arrays must match otherwise ValueError will be generated.

a = np.array([[1,2,3],[4,5,6]])
print(a)
print('\n')

print(np.append(a,[7,8,9])) # Over axis 0
print('\n')

print(np.append(a,[[5,5,5],[7,8,9]], axis=1))

[[1 2 3]
 [4 5 6]]


[1 2 3 4 5 6 7 8 9]


[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [126]:

# numpy.insert(arr, obj, values, axis)

a = np.array([[1,2],[3,4],[5,6]])
print(a)
print('\n')

print(np.insert(a,3,[11,12]))
print('\n')
# if the axis is not mentioned, the input array is flattened.

print(np.insert(a,1,[11],axis = 0))
print('\n')

print(np.insert(a,1,11,axis = 1))

[[1 2]
 [3 4]
 [5 6]]


[ 1  2  3 11 12  4  5  6]


[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [129]:
# numpy.delete(arr, obj, axis)

a = np.arange(12).reshape(3,4) 
print(a)
print('\n')

print(np.delete(a,5))
print('\n')
# if the axis is not mentioned, the input array is flattened.

print(np.delete(a,1,axis = 0))
print('\n')

print(np.delete(a,1,axis = 1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[ 0  1  2  3  4  6  7  8  9 10 11]


[[ 0  1  2  3]
 [ 8  9 10 11]]


[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [145]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
print(a)
print('\n')

print(np.unique(a)) # Returns array of unique values
print('\n')

print(np.unique(a, return_index = True)) # Returns array of Unique Values and also array of its Indicies
values,indices = np.unique(a, return_index = True)
print(indices)
print('\n')

print(np.unique(a,return_inverse= True))# Returns array of Unique Values and also array of  Indicies
values,indices = np.unique(a,return_inverse= True)
print(indices)
print(values[indices])
print('\n')

print(np.unique(a,return_counts = True))# Returns array of Unique Values and also array countof repetions respective to the order in the array 
values,counts = np.unique(a,return_counts = True)
print(counts)

[5 2 6 2 7 5 6 8 2 9]


[2 5 6 7 8 9]


(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 4, 7, 9], dtype=int64))
[1 0 2 4 7 9]


(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 0, 3, 1, 2, 4, 0, 5], dtype=int64))
[1 0 2 0 3 1 2 4 0 5]
[5 2 6 2 7 5 6 8 2 9]


(array([2, 5, 6, 7, 8, 9]), array([3, 2, 2, 1, 1, 1], dtype=int64))
[3 2 2 1 1 1]


# Binary Operators

In [153]:
a= bin(13)
print(a)
print('\n')

b=bin(14)
print(b)
print('\n')

0b1101


0b1110




In [160]:
print(np.bitwise_and(13,14))
print('\n')

print(np.bitwise_or(13,14))
print('\n')

print(np.invert(13))
print('\n')

print(np.left_shift(13,2))
print('\n')

print(np.right_shift(13,2))

12


15


-14


52


3


# String Functions

-  to perform vectorized string operations for arrays of dtype numpy.string_ or numpy.unicode_. They are based on the standard string functions in Python's built-in library.